version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres-devops-dummy
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    volumes:
      - my-postgres-data:/var/lib/postgresql/data

volumes:
  my-postgres-data:
